language: node_js
node_js:
- '6'
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sylxjtu@outlook.com
before_install:
- openssl aes-256-cbc -K $encrypted_563b667c3946_key -iv $encrypted_563b667c3946_iv
  -in deploy_key.enc -out deploy_key -d
