language: node_js
node_js:
- '6'
script: bash ./deploy.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL: sylxjtu@outlook.com
  - ASSET_PATH: ./
  - REMOTE_URL: https://xjtu-orange-juice.herokuapp.com
before_install:
- openssl aes-256-cbc -K $encrypted_529f76ee0a25_key -iv $encrypted_529f76ee0a25_iv
  -in deploy_key.enc -out deploy_key -d
